# Generated by Django 5.2.4 on 2025-08-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0002_popularcocktail_alcoholic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularcocktail',
            name='instructions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
