# Generated by Django 5.2.4 on 2025-08-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0003_alter_popularcocktail_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularcocktail',
            name='ingredients',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='popularcocktail',
            name='instructions',
            field=models.TextField(blank=True, default=list, null=True),
        ),
    ]
