# Generated by Django 5.2.4 on 2025-08-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0005_alter_popularcocktail_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularcocktail',
            name='ingredients',
            field=models.JSONField(default=list),
        ),
    ]
