# Generated by Django 5.2.4 on 2025-08-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0006_alter_popularcocktail_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularcocktail',
            name='ingredients',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
